#!/bin/sh

# rpm-ostree based images have a read-only system, so the following commands will fail
if grep -q "OSTREE" /etc/os-release; then
  echo "WARNING: Atomic desktop operating system detected. Skipping post-install steps."
  exit 0
fi

# Ensure Sunshine can grab images from KMS
path_to_setcap=$(which setcap)
path_to_sunshine=$(readlink -f $(which sunshine))
if [ -x "$path_to_setcap" ] ; then
  echo "$path_to_setcap cap_sys_admin+p $path_to_sunshine"
        $path_to_setcap cap_sys_admin+p $path_to_sunshine
fi

# Trigger udev rule reload for /dev/uinput
path_to_udevadm=$(which udevadm)
if [ -x "$path_to_udevadm" ] ; then
  $path_to_udevadm control --reload-rules
  $path_to_udevadm trigger --property-match=DEVNAME=/dev/uinput
fi
