---
# This file is centrally managed in https://github.com/<organization>/.github/
# Don't make changes to this file in this repo as they will be overwritten with changes made to the same file in
# the above-mentioned repo.

# All dependendencies, except git submodules, in this project are now managed by Renovate.
# See https://github.com/LizardByte/.github/blob/master/renovate-config.json5 for configuration.

version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    rebase-strategy: disabled
    schedule:
      interval: "cron"
      cronjob: "30 2 * * *"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
