# This file is used by automatic analysis in sonarqube cloud. Automatic analysis ignores sonar-project.properties.
# https://docs.sonarsource.com/sonarqube-cloud/analyzing-source-code/automatic-analysis#additional-analysis-configuration

sonar.exclusions=third-party/**, packaging/linux/flatpak/deps/**

# sonar.cfamily.reportingCppStandardOverride=c++23
