---
codecov:
  branch: master

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes

ignore:
  - "tests"
  - "third-party"
