---
name: Bug Report
description: Create a bug report to help us improve.
body:
  - type: markdown
    attributes:
      value: >
        **THIS IS NOT THE PLACE TO ASK FOR SUPPORT!**
        Please use our [Support Center](https://app.lizardbyte.dev/support) for support issues.
        Non actionable bug reports will be LOCKED and CLOSED!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
  - type: checkboxes
    attributes:
      label: Is your issue described in the documentation?
      description: Please read our [documentation](https://docs.lizardbyte.dev/projects/sunshine)
      options:
        - label: I have read the documentation
  - type: dropdown
    attributes:
      label: Is your issue present in the latest beta/pre-release?
      description: Please test the latest [pre-release](https://github.com/LizardByte/Sunshine/releases).
      options:
        - "I didn't read the issue template"
        - "I'm too lazy to test"
        - "This issue is present in the latest pre-release"
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: |
        A clear and concise description of the bug, list the reproduction steps.
        :warning: Errors in log messages are NOT bugs. Read the message and fix what it's telling you. :warning:
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the bug here.
  - type: dropdown
    id: os
    attributes:
      label: Host Operating System
      description: What version operating system are you running the software on?
      options:
        - Docker
        - FreeBSD
        - Linux
        - macOS
        - Windows
        - other, n/a
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: Operating System Version
      description: Provide the version of the operating system. Additionally a build number would be helpful.
    validations:
      required: true
  - type: dropdown
    id: os-architecture
    attributes:
      label: Architecture
      options:
        - amd64/x86_64
        - arm64/aarch64
        - other, n/a
    validations:
      required: true
  - type: dropdown
    id: package_type
    attributes:
      label: Package
      description: The package you installed
      options:
        - Linux - AppImage
        - Linux - AUR (Third Party)
        - Linux - deb
        - Linux - Docker
        - Linux - Fedora Copr
        - Linux - flathub/flatpak
        - Linux - Homebrew
        - Linux - LizardByte/pacman-repo
        - Linux - nixpkgs (Third Party)
        - Linux - pkg.tar.zst
        - Linux - solus (Third Party)
        - Linux - Unraid (Third Party)
        - macOS - Homebrew
        - Windows - Chocolatey (Third Party)
        - Windows - exe installer
        - Windows - msi installer (recommended)
        - Windows - portable (NOT recommended)
        - Windows - Scoop (Third Party)
        - Windows - Winget
        - other (not listed)
        - other (self built)
        - other (fork of this repo)
        - n/a
    validations:
      required: true
  - type: dropdown
    id: graphics_type
    attributes:
      label: GPU Type
      description: The type of the installed graphics card.
      options:
        - AMD
        - Apple Silicon
        - Intel
        - NVIDIA
        - Qualcomm (mediafoundation)
        - none (software encoding)
        - n/a
    validations:
      required: true
  - type: input
    id: graphics_model
    attributes:
      label: GPU Model
      description: The model of the installed graphics card.
    validations:
      required: true
  - type: input
    id: graphics_driver
    attributes:
      label: GPU Driver/Mesa Version
      description: The driver/mesa version of the installed graphics card.
    validations:
      required: true
  - type: dropdown
    id: capture_method
    attributes:
      label: Capture Method
      description: The capture method being used.
      options:
        - AVCaptureScreen (macOS)
        - KMS (Linux)
        - NvFBC (Linux)
        - wlroots (Linux)
        - X11 (Linux)
        - XDG Portal Grab (Linux)
        - Desktop Duplication API (Windows)
        - Windows.Graphics.Capture (Windows)
    validations:
      required: false
  - type: textarea
    id: apps
    attributes:
      label: Apps
      description: |
        If this is an issue with launching a game or app, please copy and paste your `apps.json` file.
      render: json
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: |
        Copy and paste logs from web-ui troubleshooting page.
        This will be automatically formatted into code, so no need for backticks.
        :warning: If full logs are not provided, the issue will be closed! :warning:
      render: shell
    validations:
      required: false
  - type: input
    id: logs_link
    attributes:
      label: Online logs
      description: |
        If logs are too long to include in the field above,
        create a [gist](https://gist.github.com/) of the logs and paste the link here.
    validations:
      required: false
