---
name: Bug Report
description: Create a bug report to help us improve.
body:
  - type: markdown
    attributes:
      value: >
        **THIS IS NOT THE PLACE TO ASK FOR SUPPORT!**
        Please use our [Support Center](https://app.lizardbyte.dev/support) for support issues.
        Non actionable bug reports will be LOCKED and CLOSED!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
  - type: checkboxes
    attributes:
      label: Is your issue described in the documentation?
      description: Please read our [documentation](https://docs.lizardbyte.dev/projects/sunshine)
      options:
        - label: I have read the documentation
  - type: dropdown
    attributes:
      label: Is your issue present in the latest beta/pre-release?
      description: Please test the latest [pre-release](https://github.com/LizardByte/Sunshine/releases).
      options:
        - "I didn't read the issue template"
        - "I'm too lazy to test"
        - "This issue is present in the latest pre-release"
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of the bug, list the reproduction steps.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the bug here.
  - type: dropdown
    id: os
    attributes:
      label: Host Operating System
      description: What version operating system are you running the software on?
      options:
        - Docker
        - Linux
        - macOS
        - Windows
        - other, n/a
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: Operating System Version
      description: Provide the version of the operating system. Additionally a build number would be helpful.
    validations:
      required: true
  - type: dropdown
    id: os-architecture
    attributes:
      label: Architecture
      options:
        - 32 bit
        - 64 bit
        - arm
        - other, n/a
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Sunshine commit or version
      description: |
        Use `sunshine --verison` to get the version, or get the version from web UI.
        Please don't just copy the latest commit from our repo, if that's not the commit you're actually using.
    validations:
      required: true
  - type: dropdown
    id: package_type
    attributes:
      label: Package
      description: The package you installed
      options:
        - Linux - AppImage
        - Linux - AUR (Third Party)
        - Linux - deb
        - Linux - Docker
        - Linux - flathub (Third Party)
        - Linux - flatpak
        - Linux - Homebrew
        - Linux - nixpkgs (Third Party)
        - Linux - pkg.tar.zst
        - Linux - rpm
        - Linux - solus (Third Party)
        - macOS - Homebrew
        - macOS - Portfile
        - Windows - Chocolatey (Third Party)
        - Windows - installer
        - Windows - portable
        - Windows - Scoop (Third Party)
        - Windows - Winget
        - other (not listed)
        - other (self built)
        - other (fork of this repo)
        - n/a
    validations:
      required: true
  - type: dropdown
    id: graphics_type
    attributes:
      label: GPU Type
      description: The type of the installed graphics card.
      options:
        - AMD
        - Intel
        - Nvidia
        - none (software encoding)
        - n/a
    validations:
      required: true
  - type: input
    id: graphics_model
    attributes:
      label: GPU Model
      description: The model of the installed graphics card.
    validations:
      required: true
  - type: input
    id: graphics_driver
    attributes:
      label: GPU Driver/Mesa Version
      description: The driver/mesa version of the installed graphics card.
    validations:
      required: true
  - type: dropdown
    id: capture_method
    attributes:
      label: Capture Method
      description: The capture method being used.
      options:
        - AVCaptureScreen (macOS)
        - KMX (Linux)
        - NvFBC (Linux)
        - wlroots (Linux)
        - X11 (Linux)
        - Desktop Duplication API (Windows)
        - Windows.Graphics.Capture (Windows)
    validations:
      required: false
  - type: textarea
    id: config
    attributes:
      label: Config
      description: |
        Please copy and paste your config (`sunshine.conf`) file.
      render: Shell
    validations:
      required: true
  - type: textarea
    id: apps
    attributes:
      label: Apps
      description: |
        If this is an issue with launching a game or app, please copy and paste your `apps.json` file.
      render: json
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. This will be automatically formatted into code,
        so no need for backticks.
      render: shell
    validations:
      required: true
