#!/bin/sh

export GROUP_INPUT=input

if [ -f /etc/group ]; then
        if ! grep -q $GROUP_INPUT /etc/group; then
                echo "Creating group $GROUP_INPUT"

                groupadd $GROUP_INPUT
        fi
else
        echo "Warning: /etc/group not found"
fi

if [ -f /etc/sunshine/sunshine.conf.old ]; then
	echo "Restoring old sunshine.conf"
	mv /etc/sunshine/sunshine.conf.old /etc/sunshine/sunshine.conf
fi

if [ -f /etc/sunshine/apps_linux.json.old ]; then
	echo "Restoring old apps_linux.json"
	mv /etc/sunshine/apps_linux.json.old /etc/sunshine/apps_linux.json
fi

# Update permissions on config files for Web Manager
if [ -f /etc/sunshine/apps_linux.json ]; then
	echo "chmod 666 /etc/sunshine/apps_linux.json"
	chmod 666 /etc/sunshine/apps_linux.json
fi

if [ -f /etc/sunshine/sunshine.conf ]; then
	echo "chmod 666 /etc/sunshine/sunshine.conf"
	chmod 666 /etc/sunshine/sunshine.conf
fi

# Ensure Sunshine can grab images from KMS
path_to_setcap=$(which setcap)
if [ -x "$path_to_setcap" ] ; then
  echo "$path_to_setcap cap_sys_admin+p /usr/bin/sunshine"
	$path_to_setcap cap_sys_admin+p $(readlink -f /usr/bin/sunshine)
fi
