if (WIN32)
elseif (APPLE)
elseif (UNIX)
    include(GNUInstallDirs)

    if(NOT DEFINED SUNSHINE_EXECUTABLE_PATH)
        set(SUNSHINE_EXECUTABLE_PATH "sunshine")
    endif()

    if(SUNSHINE_BUILD_FLATPAK)
        set(SUNSHINE_SERVICE_START_COMMAND "ExecStart=${PROJECT_FQDN}")
        set(SUNSHINE_SERVICE_STOP_COMMAND "ExecStop=flatpak kill ${PROJECT_FQDN}")
    else()
        set(SUNSHINE_SERVICE_START_COMMAND "ExecStart=${SUNSHINE_EXECUTABLE_PATH}")
        set(SUNSHINE_SERVICE_STOP_COMMAND "")
    endif()
endif ()
