if (WIN32)
elseif (APPLE)
    if (NOT SUNSHINE_BUILD_HOMEBREW)
        set(CMAKE_BUILD_WITH_INSTALL_RPATH ON)
        set(CMAKE_INSTALL_RPATH "")
        set(CMAKE_INSTALL_RPATH_USE_LINK_PATH FALSE)
    endif()
elseif (UNIX)
    include(GNUInstallDirs)

    if(NOT DEFINED SUNSHINE_EXECUTABLE_PATH)
        set(SUNSHINE_EXECUTABLE_PATH "sunshine")
    endif()

    if(SUNSHINE_BUILD_FLATPAK)
        set(SUNSHINE_SERVICE_START_COMMAND "ExecStart=flatpak run --command=sunshine ${PROJECT_FQDN}")
        set(SUNSHINE_SERVICE_STOP_COMMAND "ExecStop=flatpak kill ${PROJECT_FQDN}")
    else()
        set(SUNSHINE_SERVICE_START_COMMAND "ExecStart=${SUNSHINE_EXECUTABLE_PATH}")
        set(SUNSHINE_SERVICE_STOP_COMMAND "")
    endif()
endif()
