#!/bin/bash -e
set -e

CMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE:-Release}"
SUNSHINE_EXECUTABLE_PATH="${SUNSHINE_EXECUTABLE_PATH:-/usr/bin/sunshine}"
SUNSHINE_ROOT="${SUNSHINE_ROOT:-/root/sunshine}"
CMAKE_INSTALL_PREFIX="${CMAKE_INSTALL_PREFIX:-/etc}"
SUNSHINE_ASSETS_DIR="${SUNSHINE_ASSETS_DIR:-sunshine/assets}"
SUNSHINE_CONFIG_DIR="${SUNSHINE_CONFIG_DIR:-sunshine/config}"

SUNSHINE_ENABLE_WAYLAND=${SUNSHINE_ENABLE_WAYLAND:-ON}
SUNSHINE_ENABLE_X11=${SUNSHINE_ENABLE_X11:-ON}
SUNSHINE_ENABLE_DRM=${SUNSHINE_ENABLE_DRM:-ON}
SUNSHINE_ENABLE_CUDA=${SUNSHINE_ENABLE_CUDA:-ON}

if [[ ! -d /root/sunshine-build ]]; then
  mkdir -p /root/sunshine-build
fi
cd /root/sunshine-build

cmake \
  "-DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE" \
  "-DSUNSHINE_EXECUTABLE_PATH=$SUNSHINE_EXECUTABLE_PATH" \
  "-DSUNSHINE_ENABLE_WAYLAND=$SUNSHINE_ENABLE_WAYLAND" \
  "-DSUNSHINE_ENABLE_X11=$SUNSHINE_ENABLE_X11" \
  "-DSUNSHINE_ENABLE_DRM=$SUNSHINE_ENABLE_DRM" \
  "-DSUNSHINE_ENABLE_CUDA=$SUNSHINE_ENABLE_CUDA" \
  "-DCMAKE_INSTALL_PREFIX=$CMAKE_INSTALL_PREFIX" \
  "-DSUNSHINE_ASSETS_DIR=$SUNSHINE_ASSETS_DIR" \
  "-DSUNSHINE_CONFIG_DIR=$SUNSHINE_CONFIG_DIR" \
  "$SUNSHINE_ROOT"

make -j ${nproc}
