FROM ubuntu:18.04 AS sunshine-ubuntu_18_04

ARG DEBIAN_FRONTEND=noninteractive 
ARG TZ="Europe/London"

RUN add-apt-repository ppa:ubuntu-toolchain-r/test && \
    apt-get update -y && \
    apt-get install -y --no-install-recommends \
                        build-essential \
                        cmake \
                        gcc-10 \
                        git \
                        g++-10 \
                        libavdevice-dev \
                        libboost-thread-dev \
                        libboost-filesystem-dev \
                        libboost-log-dev \
                        libcap-dev \
                        libdrm-dev \
                        libevdev-dev \
                        libpulse-dev \
                        libopus-dev \
                        libssl-dev \
                        libwayland-dev \
                        libx11-dev \
                        libxcb-shm0-dev \
                        libxcb-xfixes0-dev \
                        libxcb1-dev \
                        libxfixes-dev \
                        libxrandr-dev \
                        libxtst-dev \
                        software-properties-common \
                        wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN cp /usr/bin/gcc-10 /usr/bin/gcc && cp /usr/bin/g++-10 /usr/bin/gcc-10

RUN wget https://developer.download.nvidia.com/compute/cuda/11.4.2/local_installers/cuda_11.4.2_470.57.02_linux.run --progress=bar:force:noscroll -q --show-progress -O /root/cuda.run && chmod a+x /root/cuda.run
RUN /root/cuda.run --silent --toolkit --toolkitpath=/usr --no-opengl-libs --no-man-page --no-drm && rm /root/cuda.run

COPY build-private.sh /root/build.sh


ENTRYPOINT ["/root/build.sh"]
