FROM ubuntu:18.04 AS sunshine-ubuntu_18_04

ARG DEBIAN_FRONTEND=noninteractive 
ARG TZ="Europe/London"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update -y && \
    apt-get install -y \
        apt-transport-https \
        ca-certificates \
        gnupg \
        software-properties-common \
        wget \
    && wget -qO - https://apt.kitware.com/keys/kitware-archive-latest.asc | apt-key add - && \
    add-apt-repository 'deb https://apt.kitware.com/ubuntu/ bionic main' && \
    add-apt-repository ppa:ubuntu-toolchain-r/test && \
    add-apt-repository ppa:savoury1/graphics && \
    add-apt-repository ppa:savoury1/multimedia && \
    add-apt-repository ppa:savoury1/ffmpeg4 && \
    apt-get update -y && \
    apt-get install -y \
        build-essential \
        cmake \
        ffmpeg \
        gcc-10 \
        git \
        g++-10 \
        libavdevice-dev \
        libboost-filesystem-dev \
        libboost-log-dev \
        libboost-regex-dev \
        libboost-thread-dev \
        libcap-dev \
        libdrm-dev \
        libevdev-dev \
        libpulse-dev \
        libopus-dev \
        libssl-dev \
        libwayland-dev \
        libx11-dev \
        libxcb-shm0-dev \
        libxcb-xfixes0-dev \
        libxcb1-dev \
        libxfixes-dev \
        libxrandr-dev \
        libxtst-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10

RUN wget https://developer.download.nvidia.com/compute/cuda/11.4.2/local_installers/cuda_11.4.2_470.57.02_linux.run --progress=bar:force:noscroll -q --show-progress -O /root/cuda.run && chmod a+x /root/cuda.run
RUN /root/cuda.run --silent --toolkit --toolkitpath=/usr --no-opengl-libs --no-man-page --no-drm && rm /root/cuda.run

RUN mkdir glibc-src && cd glibc-src && \
    wget http://ftp.gnu.org/gnu/libc/glibc-2.31.tar.gz && \
    tar -xvzf glibc-2.31.tar.gz && \
    mkdir build && cd build && \
    ../glibc-src/glibc-2.31/configure --prefix=/usr/glibc && \
    make && \
    make install

COPY build-private.sh /root/build.sh


ENTRYPOINT ["/root/build.sh"]
