FROM fedora:33 AS sunshine-fedora_33

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN dnf -y update && \
    dnf -y group install "Development Tools" && \
    dnf -y install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm && \
    dnf -y install \
        boost-devel \
        boost-static.x86_64 \
        cmake \
        ffmpeg-devel \
        libevdev-devel \
        libxcb-devel \
        libX11-devel \
        libXfixes-devel \
        libXrandr-devel \
        libXtst-devel \
        openssl-devel \
        opus-devel \
        pulseaudio-libs-devel \
    && dnf clean all \
    && rm -rf /var/cache/yum

# https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Fedora&target_version=35&target_type=runfile_local
RUN wget https://developer.download.nvidia.com/compute/cuda/11.6.0/local_installers/cuda_11.6.0_510.39.01_linux.run --progress=bar:force:noscroll -q --show-progress -O /root/cuda.run && chmod a+x /root/cuda.run
RUN /root/cuda.run --silent --toolkit --toolkitpath=/usr --no-opengl-libs --no-man-page --no-drm && rm /root/cuda.run

COPY build-private.sh /root/build.sh


ENTRYPOINT ["/root/build.sh"]
