FROM debian:bullseye AS sunshine-debian

ARG DEBIAN_FRONTEND=noninteractive 
ARG TZ="Europe/London"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN echo deb http://deb.debian.org/debian/ bullseye main contrib non-free | tee /etc/apt/sources.list.d/non-free.list
RUN apt-get update -y && \
    apt-get install -y \
        build-essential \
        cmake \
        git \
        libavdevice-dev \
        libboost-thread-dev \
        libboost-filesystem-dev \
        libboost-log-dev \
        libcap-dev \
        libdrm-dev \
        libevdev-dev \
        libpulse-dev \
        libopus-dev \
        libssl-dev \
        libwayland-dev \
        libx11-dev \
        libxcb-shm0-dev \
        libxcb-xfixes0-dev \
        libxcb1-dev \
        libxfixes-dev \
        libxrandr-dev \
        libxtst-dev \
        nvidia-cuda-dev \
        nvidia-cuda-toolkit \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY build-private.sh /root/build.sh


ENTRYPOINT ["/root/build.sh"]

ENTRYPOINT ["/root/sunshine-build/gen-deb"]
