FROM fedora:33 AS sunshine-fedora_33

# Fedora 33 end of life is November 2021
# This file remains for reference only

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN dnf -y update && \
    dnf -y group install "Development Tools" && \
    dnf -y install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm && \
    dnf -y install \
        boost-devel \
        boost-static.x86_64 \
        cmake \
        ffmpeg-devel \
        libevdev-devel \
        libxcb-devel \
        libX11-devel \
        libXfixes-devel \
        libXrandr-devel \
        libXtst-devel \
        openssl-devel \
        opus-devel \
        pulseaudio-libs-devel \
        rpm-build \
    && dnf clean all \
    && rm -rf /var/cache/yum

# Entrypoint
COPY build-private.sh /root/build.sh
ENTRYPOINT ["/root/build.sh", "-rpm"]
