---
name: Publish Artifacts

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions: {}

jobs:
  publish:
    if: >-
      github.event.workflow_run.event == 'pull_request' &&
      (github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure')
    permissions:
      actions: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Publish PR artifacts
        uses: LizardByte/actions/actions/artifact_comment@aef56a192d51ec7445b29117a32b9bd25d2b103c  # v2026.829.140353
        with:
          artifact_patterns: build-*
