---
name: Publish Artifacts

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions: {}

jobs:
  publish:
    if: >-
      github.event.workflow_run.event == 'pull_request' &&
      (github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure')
    permissions:
      actions: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Publish PR artifacts
        uses: LizardByte/actions/actions/artifact_comment@188c8ccad593e0f68bcf6aacb6bf84f10359d26f  # v2026.905.43751
        with:
          artifact_patterns: build-*
