---
name: Publish Artifacts

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions: {}

jobs:
  publish:
    if: >-
      github.event.workflow_run.event == 'pull_request' &&
      (github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure')
    permissions:
      actions: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Publish PR artifacts
        uses: LizardByte/actions/actions/artifact_comment@28374bf43cc8b6ee88b9b8a3419b2ac7a6573906  # v2026.928.123224
        with:
          artifact_patterns: build-*
